/**
 * API Route for Report Support
 * 
 * POST /api/reports/[id]/support - Add support to a report
 * GET /api/reports/[id]/support?token=... - Check if already supported
 * Uses SECURITY DEFINER RPCs to avoid exposing supporter tokens
 * Tokens are UUIDs generated by crypto.randomUUID()
 */

import { NextRequest, NextResponse } from 'next/server';
import { supabase } from '@/lib/supabase-client';

export const dynamic = 'force-dynamic';

// POST - Add support to a report
export async function POST(
  request: NextRequest,
  { params }: { params: { id: string } }
) {
  try {
    const { id } = params;
    const body = await request.json();
    const { token } = body;

    if (!token) {
      return NextResponse.json(
        { error: 'Missing supporter token' },
        { status: 400 }
      );
    }

    console.log('[ADD_SUPPORT] reportId=', id, 'token=', token.substring(0, 8));

    // Call the SECURITY DEFINER function to add support
    const { data, error } = await supabase.rpc('add_report_support', {
      p_report_id: id,
      p_token: token,
    });

    if (error) {
      console.error('[ADD_SUPPORT_ERROR]', error);
      return NextResponse.json(
        { error: 'Failed to add support', details: error.message },
        { status: 500 }
      );
    }

    console.log('[ADD_SUPPORT_RESULT] success=', data);

    return NextResponse.json({
      success: true,
      alreadySupported: !data,  // false means new support, true means already supported
    });
  } catch (error) {
    console.error('[ADD_SUPPORT_EXCEPTION]', error);
    return NextResponse.json(
      { error: 'Internal server error' },
      { status: 500 }
    );
  }
}

// GET - Check if already supported
export async function GET(
  request: NextRequest,
  { params }: { params: { id: string } }
) {
  try {
    const { id } = params;
    const { searchParams } = new URL(request.url);
    const token = searchParams.get('token');

    if (!token) {
      return NextResponse.json(
        { error: 'Missing supporter token' },
        { status: 400 }
      );
    }

    console.log('[CHECK_SUPPORT] reportId=', id, 'token=', token.substring(0, 8));

    // Call the SECURITY DEFINER function to check support status
    const { data, error } = await supabase.rpc('has_supported_report', {
      p_report_id: id,
      p_token: token,
    });

    if (error) {
      console.error('[CHECK_SUPPORT_ERROR]', error);
      return NextResponse.json(
        { error: 'Failed to check support status', details: error.message },
        { status: 500 }
      );
    }

    console.log('[CHECK_SUPPORT_RESULT] hasSupported=', data);

    return NextResponse.json({
      success: true,
      hasSupported: data,
    });
  } catch (error) {
    console.error('[CHECK_SUPPORT_EXCEPTION]', error);
    return NextResponse.json(
      { error: 'Internal server error' },
      { status: 500 }
    );
  }
}
