/**
 * Supporter Token Management
 * 
 * Manages privacy-safe anonymous tokens for collective reports feature.
 * Uses localStorage to persist a unique UUID token per browser/device.
 */

const STORAGE_KEY = 'aqtau_supporter_token';

/**
 * Get or create a supporter token for the current browser
 * Returns a UUID string generated by crypto.randomUUID()
 */
export function getSupporterToken(): string {
  // Try to get existing token from localStorage
  if (typeof window !== 'undefined') {
    const existing = localStorage.getItem(STORAGE_KEY);
    if (existing) {
      return existing;
    }

    // Create new token if none exists
    const newToken = crypto.randomUUID();
    localStorage.setItem(STORAGE_KEY, newToken);
    return newToken;
  }

  // Fallback for server-side (shouldn't happen in normal flow)
  return crypto.randomUUID();
}

/**
 * Check if a supporter token exists
 */
export function hasSupporterToken(): boolean {
  if (typeof window !== 'undefined') {
    return localStorage.getItem(STORAGE_KEY) !== null;
  }
  return false;
}
